---

- name: install yum-utils
  yum:
    name: yum-utils
    state: present

- name: install docker repository
  command:  yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo

- name: make sure docker from distro is not installed
  yum:
    name: "{{ item }}"
    state: absent
  with_items:
    - docker
    - docker-common
    - container-selinux
    - docker-selinux
    - docker-engine

- name: Install docker
  yum:
    name: "{{ item }}"
    state: latest
  with_items:
    - docker-ce
    - python-docker-py


- replace:
    path: "{{docker_service}}"
    regexp: '{{find_execstart}}'
    replace: '{{replace_execstart}}'
    backup: no

- name: reload systemctl
  command: systemctl daemon-reload

- name: restart docker service
  command: systemctl restart docker

- name: making sure pip installed
  shell: curl -sSL https://bootstrap.pypa.io/get-pip.py | python
